import os
import shutil
import subprocess
from datetime import datetime
from feedgen.feed import FeedGenerator

# --- CONFIGURATION ---
GITHUB_USER = "sheascan"
REPO_NAME = "my-daily-briefing"
TEST_FOLDER_NAME = "final_victory" 
XML_FILENAME = "feed.xml"  # Simple, standard name

# Calculated Paths
BASE_DIR = os.path.dirname(os.path.abspath(__file__))
GIT_HOSTING_DIR = os.path.join(BASE_DIR, "hosting")
TEST_DIR = os.path.join(GIT_HOSTING_DIR, TEST_FOLDER_NAME)
PUBLIC_URL_BASE = f"https://{GITHUB_USER}.github.io/{REPO_NAME}/{TEST_FOLDER_NAME}/"
FULL_FEED_URL = f"{PUBLIC_URL_BASE}{XML_FILENAME}"

# Real Audio from your repo
REAL_AUDIO_URL = f"https://{GITHUB_USER}.github.io/{REPO_NAME}/21Dec/21Dec_0855_best_offer_ever.mp3"

def run_experiment():
    print("🧪 STARTING FINAL COMPLIANCE RUN...")
    
    if not os.path.exists(GIT_HOSTING_DIR):
        print("❌ Error: 'hosting' folder missing.")
        return

    if os.path.exists(TEST_DIR):
        shutil.rmtree(TEST_DIR)
    os.makedirs(TEST_DIR)
    
    print("   XML Building compliant feed...")
    fg = FeedGenerator()
    fg.load_extension('podcast')
    
    # Metadata
    fg.title(f"DAILY BRIEFING LIVE {datetime.now().strftime('%H:%M')}")
    fg.link(href=PUBLIC_URL_BASE, rel='alternate')
    fg.description("Daily executive summary of the most important news, generated by AI.")
    fg.language("en")
    
    # --- THE MISSING LINK (Restored) ---
    # This tells Pocket Casts: "I am the authoritative source for this feed"
    fg.link(href=FULL_FEED_URL, rel='self')
    # -----------------------------------

    # Compliance Tags
    fg.podcast.itunes_category('Technology')
    fg.podcast.itunes_explicit('no')
    # Using a larger standard placeholder image (1400x1400) to ensure size compliance
    fg.podcast.itunes_image('https://via.placeholder.com/1400x1400.png?text=Briefing')
    
    fg.podcast.itunes_owner(name="Mike M", email="mike@test.com")
    fg.podcast.itunes_author("Mike M")
    
    # Episode
    fe = fg.add_entry()
    fe.title("Briefing: Best Offer Ever")
    fe.id(f"victory_id_{datetime.now().timestamp()}") # Unique ID
    fe.link(href=REAL_AUDIO_URL)
    fe.enclosure(REAL_AUDIO_URL, "9818514", 'audio/mpeg') 
    
    # Save
    fg.rss_file(os.path.join(TEST_DIR, XML_FILENAME))

    # Push
    print("   🚀 Pushing to GitHub...")
    os.chdir(GIT_HOSTING_DIR)
    subprocess.run(["git", "add", "."], check=True)
    subprocess.run(["git", "commit", "-m", "Deploy Victory Run"], check=False)
    subprocess.run(["git", "push"], check=True)
    
    print("\n✅ DEPLOYED!")
    print(f"   🔗 URL: {FULL_FEED_URL}")
    print("   ⏳ WAITING ROOM: You must wait 3 minutes before testing.")

if __name__ == "__main__":
    run_experiment()