import os
import shutil
import subprocess
from datetime import datetime
from feedgen.feed import FeedGenerator

# --- CONFIGURATION ---
GITHUB_USER = "sheascan"
REPO_NAME = "my-daily-briefing"
TEST_FOLDER_NAME = "live_feed_v1" 
XML_FILENAME = "podcast_live.xml"  # <--- NEW NAME to clear cache

# Paths
BASE_DIR = os.path.dirname(os.path.abspath(__file__))
GIT_HOSTING_DIR = os.path.join(BASE_DIR, "hosting")
TEST_DIR = os.path.join(GIT_HOSTING_DIR, TEST_FOLDER_NAME)
PUBLIC_URL_BASE = f"https://{GITHUB_USER}.github.io/{REPO_NAME}/{TEST_FOLDER_NAME}/"
FULL_FEED_URL = f"{PUBLIC_URL_BASE}{XML_FILENAME}"

# Real Audio Link
REAL_AUDIO_URL = f"https://{GITHUB_USER}.github.io/{REPO_NAME}/21Dec/21Dec_0855_best_offer_ever.mp3"

def run_experiment():
    print("🧪 STARTING FINAL IMAGE FIX RUN...")
    
    if not os.path.exists(GIT_HOSTING_DIR):
        print("❌ Error: 'hosting' folder missing.")
        return

    if os.path.exists(TEST_DIR):
        shutil.rmtree(TEST_DIR)
    os.makedirs(TEST_DIR)
    
    print("   XML Building feed with KNOWN GOOD IMAGE...")
    fg = FeedGenerator()
    fg.load_extension('podcast')
    
    # Metadata
    fg.title(f"DAILY BRIEFING {datetime.now().strftime('%H:%M')}")
    fg.link(href=PUBLIC_URL_BASE, rel='alternate')
    fg.description("Daily executive summary of the most important news, generated by AI.")
    fg.language("en")
    
    # 1. The Critical Self Link
    fg.link(href=FULL_FEED_URL, rel='self')

    # 2. The Critical Image (Reverted to GitHub Logo which passed validation)
    fg.podcast.itunes_image('https://github.githubassets.com/images/modules/logos_page/GitHub-Mark.png')
    
    # 3. Compliance Tags
    fg.podcast.itunes_category('Technology')
    fg.podcast.itunes_explicit('no')
    fg.podcast.itunes_owner(name="Mike M", email="mike@test.com")
    fg.podcast.itunes_author("Mike M")
    
    # Episode
    fe = fg.add_entry()
    fe.title("Briefing: Best Offer Ever")
    fe.id(f"live_id_{datetime.now().timestamp()}")
    fe.link(href=REAL_AUDIO_URL)
    fe.enclosure(REAL_AUDIO_URL, "9818514", 'audio/mpeg') 
    
    # Save
    fg.rss_file(os.path.join(TEST_DIR, XML_FILENAME))

    # Push
    print("   🚀 Pushing to GitHub...")
    os.chdir(GIT_HOSTING_DIR)
    subprocess.run(["git", "add", "."], check=True)
    subprocess.run(["git", "commit", "-m", "Deploy Final Image Fix"], check=False)
    subprocess.run(["git", "push"], check=True)
    
    print("\n✅ DEPLOYED!")
    print(f"   🔗 URL: {FULL_FEED_URL}")
    print("   ⏳ WAIT 3 MINUTES before testing.")

if __name__ == "__main__":
    run_experiment()